site_name: PStomo

nav:
    - Home: index.md
    - Parameters: parameters.md
    - File formats: formats.md
    - Tutorials: tutorials.md
    - About: about.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme: readthedocs
